export const items =  [
    {
      id: 1,
      category: 'mobiles',
      title: "Intel I9 Gaming Pc",
      imgSrc: 'https://m.media-amazon.com/images/I/615zTIQKzXL._SL1000_.jpg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Core I9 Processor,32Gb Ram,240Gb Ssd,4Tb Hard Drive,4Gb Graphic Card,',
      price: '85,999'
    },
    {
      id: 5,
      category: 'laptops',
      title: "CHIST I7 Extreme Gaming PC Full Setup",
      imgSrc: 'https://m.media-amazon.com/images/I/51ngjc+7SPL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: '6TH Gen Core i7 6700 Processor 4Core 8 Threats/DDR4 32GB RAM/512GB SSD 1TB HDD/GT 730 DDR5 Graphic Card/22 Inch... ',
      price: '46,999',
    },
    {
      id: 7,
      category: 'tablets',
      title: "T-Force Delta TUF DDR4 16GB",
      imgSrc: 'https://m.media-amazon.com/images/I/6173d68fKnL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: '3200MHz (PC4-25600) CL16 Desktop Gaming Memory Module ram - TF9D416G3200HC16FDC01 - （TUF Alliance RGB Module）',
      price: '5,500',
    },
    {
      id: 2,
      category: 'mobiles',
      title: "AMD 7000 Series Ryzen 9 7950X Desktop Processor ",
      imgSrc: 'https://m.media-amazon.com/images/I/31pgfatL1yL._SL500_.jpg',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: '16 cores 32 Threads 80 MB Cache 4.5 GHz Up to 5.7 GHz Socket AM5, 600 Series Chipset (100-100000514WOF)',
      price: '52,900',
    },
    {
      id: 6,
      category: 'tablets',
      title: "ZEBRONICS ZIUM Mid-Tower Gaming Cabinet",
      imgSrc: 'https://m.media-amazon.com/images/I/81NvqrYWevL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'M-ATX/M-Itx, Fins Focussed Multicolor Rear Fan, Multi Color Led Strip, Acrylic Glass Side Panel, USB 3.0, USB 2.0',
      price: '1699',
    },
    {
      id: 3,
      category: 'mobiles',
      title: "MSI B450 Gaming Plus MAXATX Gaming Motherboard",
      imgSrc: 'https://m.media-amazon.com/images/I/61+TlfATKyL._SL1024_.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'MSI B450 Gaming Plus MAXATX Gaming Motherboard Socket AM4 DDR4',
      price: '9000',
    },
    {
      id: 4,
      category: 'laptops',
      title: "reo Beluga 3.5mm Over-Ear Wired Gaming Headphone ",
      imgSrc: 'https://m.media-amazon.com/images/I/61dlwkrh2eL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Kreo Beluga 3.5mm Over-Ear Wired Gaming Headphone with ANC Mic | Premium Sound Quality with 50mm Drivers | Gaming Headphones with Cooling Gel Earpads |... ',
      price: '2,499',
    },
    {
      id: 9,
      category: 'tablets',
      title: "Ant Esports KM500W Gaming Backlit Keyboard and Mouse Combo",
      imgSrc: 'https://m.media-amazon.com/images/I/61B3tl7HEBL._AC_UY218_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Ant Esports KM500W Gaming Backlit Keyboard and Mouse ComboLED Wired Gaming Keyboard, Ergonomic & Wrist Rest Keyboard, Programmable Gaming Mouse for',
      price: '1269',
    },
    {
      id: 8,
      category: 'laptops',
      title: "ZEBRONICS Shark Lite Wireless Gaming Mouse",
      imgSrc: 'https://m.media-amazon.com/images/I/61K2ZX6suPL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'ZEBRONICS-Transformer-M with a High-Performance Gold-Plated USB Mouse: 6 Buttons, Multi-Color LED Lights,High-Resolution Sensor with max 3600 DPI, and DPI Switch(Black) ',
      price: '399',
    },


  ]